"""empty message

Revision ID: 3d1704fa8688
Revises: 
Create Date: 2018-01-29 09:56:44.156550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1704fa8688'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_department', sa.String(length=64), nullable=True),
    sa.Column('name_department', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_department')
    )
    op.create_table('Subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_subject', sa.String(length=64), nullable=True),
    sa.Column('name_subject', sa.String(length=64), nullable=True),
    sa.Column('units_subject', sa.Integer(), nullable=True),
    sa.Column('prerequisites', sa.String(length=64), nullable=True),
    sa.Column('code_department', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['code_department'], ['Departments.code_department'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_subject')
    )
    op.create_table('Books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_subject', sa.String(length=64), nullable=True),
    sa.Column('name_book', sa.String(length=128), nullable=True),
    sa.Column('type_of_book', sa.String(length=128), nullable=True),
    sa.Column('size_of_book', sa.FLOAT(), nullable=True),
    sa.Column('url_of_book', sa.String(length=260), nullable=True),
    sa.ForeignKeyConstraint(['code_subject'], ['Subjects.code_subject'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Books')
    op.drop_table('Subjects')
    op.drop_table('Departments')
    # ### end Alembic commands ###
