"""empty message

Revision ID: 50b5cfa1a900
Revises: c91931015dff
Create Date: 2018-05-08 10:37:42.478562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b5cfa1a900'
down_revision = 'c91931015dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_post', sa.String(length=64), nullable=True),
    sa.Column('title_post', sa.String(length=64), nullable=True),
    sa.Column('content_post', sa.TEXT(), nullable=True),
    sa.Column('image_post', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Posts')
    # ### end Alembic commands ###
